// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiConfig = { id?: string | null, name?: string | null, protocol: string, apiKey: string, baseUrl: string, model: string, isDefault: boolean, stream: boolean, };

export type AppConfig = { api: ApiConfig, services: Array<ApiConfig>, prompts: Array<PromptConfig>, shortcuts: Array<ShortcutConfig>, language: string, theme: string, launchOnStart: boolean, minToTray: boolean, selectionOn: boolean, escClose: boolean, clickOutside: boolean, summaryLanguage: string, diagnostics: boolean, fontScale: number, onboardingDone: boolean, };

export type PromptConfig = { id: string, name: string, content: string, model: string, shortcut?: string | null, outputFormat: string, 
/**
 * 是否为内置提示词(不可修改/删除)
 */
isBuiltin: boolean, };

export type ShortcutConfig = { id: string, accelerator: string, promptId?: string | null, action: string, name?: string | null, description?: string | null, isDefault: boolean, model?: string | null, };
