// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiConfig = { id?: string | null, name?: string | null, protocol: string, apiKey: string, baseUrl: string, model: string, isDefault: boolean, stream: boolean, 
/**
 * 额外请求参数(JSON 对象文本),深合并进请求体,用于关闭思考等厂商私有参数。
 * 留空(None) = 不附加任何参数。
 * 之所以存 String 而非 Value:保留用户原始缩进与键序,且非法 JSON 也能存住由 UI 提示修正。
 * skip_serializing_if:未使用的用户 config.json 不出现该字段,保持配置可读。
 */
extraParams?: string | null, };

export type AppConfig = { api: ApiConfig, services: Array<ApiConfig>, prompts: Array<PromptConfig>, shortcuts: Array<ShortcutConfig>, language: string, theme: string, launchOnStart: boolean, minToTray: boolean, selectionOn: boolean, escClose: boolean, clickOutside: boolean, summaryLanguage: string, diagnostics: boolean, fontScale: number, onboardingDone: boolean, onboardingStep?: number | null, historyRetention: string, };

export type PromptConfig = { id: string, name: string, content: string, model: string, shortcut?: string | null, outputFormat: string, 
/**
 * 是否为内置提示词(不可修改/删除)
 */
isBuiltin: boolean, 
/**
 * 提示词类别:summary(总结)/translate(翻译)/qa(问答)/general(通用)。
 * 决定拼接哪套系统提示词模板与历史标题解析方式。
 * 旧配置缺该字段时回退 "summary"(行为与改动前一致)。
 */
tag: string, };

export type ShortcutConfig = { id: string, accelerator: string, promptId?: string | null, action: string, name?: string | null, description?: string | null, isDefault: boolean, model?: string | null, 
/**
 * 快捷键绑定的 AI 服务 id(引用式):模型/密钥/协议均从该服务解析,
 * 改 AI 服务配置后快捷键自动跟随,无需任何回写逻辑。
 * 旧 `model` 字段为迁移遗留,已不再使用(迁移后清空)。
 */
serviceId?: string | null, 
/**
 * 快捷键级附加参数(JSON 对象文本):非空时深合并覆盖服务级 extra_params,
 * 为空则沿用服务级。用途:同一服务在不同快捷键下需要不同行为(如总结关思考、深析开思考)。
 */
extraParams?: string | null, };
