// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiConfig = { id?: string | null, name?: string | null, protocol: string, apiKey: string, baseUrl: string, model: string, isDefault: boolean, stream: boolean, };

export type AppConfig = { api: ApiConfig, services: Array<ApiConfig>, prompts: Array<PromptConfig>, shortcuts: Array<ShortcutConfig>, language: string, theme: string, launchOnStart: boolean, minToTray: boolean, selectionOn: boolean, escClose: boolean, clickOutside: boolean, summaryLanguage: string, diagnostics: boolean, fontScale: number, onboardingDone: boolean, onboardingStep?: number | null, };

export type PromptConfig = { id: string, name: string, content: string, model: string, shortcut?: string | null, outputFormat: string, 
/**
 * 是否为内置提示词(不可修改/删除)
 */
isBuiltin: boolean, 
/**
 * 提示词类别:summary(总结)/translate(翻译)/qa(问答)/general(通用)。
 * 决定拼接哪套系统提示词模板与历史标题解析方式。
 * 旧配置缺该字段时回退 "summary"(行为与改动前一致)。
 */
tag: string, };

export type ShortcutConfig = { id: string, accelerator: string, promptId?: string | null, action: string, name?: string | null, description?: string | null, isDefault: boolean, model?: string | null, serviceId?: string | null, };
